language: c

sudo: false

os:
- windows
- linux
- osx

dist: xenial

cache:
  directories:
    - .stack-work
    - $HOME/.stack
    - $HOME/haskell-ide-engine/.stack-work
    - C:/Users/travis/AppData/Local/Programs/stack
    - C:/sr
  timeout: 1000

addons:
  apt:
    packages:
      - haskell-stack
      - npm
  homebrew:
    packages:
      - haskell-stack
      - npm

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install haskell-stack nodejs; fi
  - stack upgrade --binary-only # apt dist lags behind
  - mkdir -p haskell-ide-engine
  - cd $HOME/haskell-ide-engine
  - git init
  - git remote add origin https://github.com/haskell/haskell-ide-engine.git
  - git pull origin master
  - git checkout f5c903f31ef5a7ee75984faf2e6ccc0a06ab23eb
  - git submodule init
  - git submodule sync
  - git submodule update --init
  - stack setup --silent # prevent windows logging vommit
  - stack --no-terminal --skip-ghc-check -j2 install
  - stack exec hoogle generate
  - cd $TRAVIS_BUILD_DIR
  - npm update
  - npm i -g javascript-typescript-langserver

script:
  - stack test
